export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const TOGGLE_CART = "TOGGLE_CART";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";

export const UPDATE_MEALS = "UPDATE_MEALS";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const UPDATE_SORT = "UPDATE_SORT";

export const UPDATE_DAY_PLAN = "UPDATE_DAY_PLAN";
export const TOGGLE_SHOW_DAY = "TOGGLE_SHOW_DAY";
export const REMOVE_DAY_PLAN = "REMOVE_DAY_PLAN";
export const RANDOM_DAY_PLAN = "RANDOM_DAY_PLAN";
