const { Meal } = require("../models");

const mealData = [
  {
    mealName: "Bibimbap",
    protein: 40,
    fat: 30,
    carbs: 20,
    price: 9.74,
    img: "/img/bibimbap.jpg",
  },
  {
    mealName: "chickenBake",
    protein: 22,
    fat: 10,
    carbs: 20,
    price: 11.74,
    img: "/img/chickenBake.jpg",
  },
  {
    mealName: "ChickenHummus",
    protein: 45,
    fat: 30,
    carbs: 5,
    price: 9.68,
    img: "/img/ChickenHummus.jpg",
  },
  {
    mealName: "ChickenPasta",
    protein: 15,
    fat: 12,
    carbs: 22,
    price: 14.21,
    img: "/img/ChickenPasta.jpg",
  },
  {
    mealName: "ChickenSatay",
    protein: 60,
    fat: 30,
    carbs: 30,
    price: 10.74,
    img: "/img/ChickenSatay.jpg",
  },
  {
    mealName: "pastaSalad",
    protein: 60,
    fat: 30,
    carbs: 30,
    price: 10.99,
    img: "/img/pastaSalad.jpg",
  },
  {
    mealName: "salad",
    protein: 60,
    fat: 30,
    carbs: 30,
    price: 10.74,
    img: "/img/salad.jpeg",
  },
  {
    mealName: "Bibimbap",
    protein: 41,
    fat: 30,
    carbs: 20,
    price: 9.77,
    img: "/img/bibimbap.jpg",
  },
  {
    mealName: "chickenBake",
    protein: 22,
    fat: 10,
    carbs: 20,
    price: 14.44,
    img: "/img/chickenBake.jpg",
  },
  {
    mealName: "ChickenHummus",
    protein: 55,
    fat: 30,
    carbs: 5,
    price: 9.74,
    img: "/img/ChickenHummus.jpg",
  },
  {
    mealName: "ChickenPasta",
    protein: 10,
    fat: 10,
    carbs: 20,
    price: 14.74,
    img: "/img/ChickenPasta.jpg",
  },
  {
    mealName: "ChickenSatay",
    protein: 60,
    fat: 32,
    carbs: 40,
    price: 10.12,
    img: "/img/ChickenSatay.jpg",
  },
  {
    mealName: "pastaSalad",
    protein: 60,
    fat: 30,
    carbs: 30,
    price: 10.14,
    img: "/img/pastaSalad.jpg",
  },
  {
    mealName: "salad",
    protein: 70,
    fat: 30,
    carbs: 30,
    price: 10.16,
    img: "/img/salad.jpeg",
  },
];

const seedMeals = () => Meal.bulkCreate(mealData);

module.exports = seedMeals;
